# Generated by Django 4.1.7 on 2023-02-26 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0003_rename_title_menuitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='named_url',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
    ]
